Arreglos usabilidad seccion mecanico
IgnacioToledoDev/capstone pull request #95
Opened 2024-11-06 20:37 UTC by joherrerac

2024-11-06 23:14 UTC, IgnacioToledoDev requested changes

2024-11-06 23:14 UTC, IgnacioToledoDev commented on frontend/src/app/mecanico/ajustes/ajustes.page.html
> +  <p></p>
esto por que ??

2024-11-06 23:14 UTC, IgnacioToledoDev commented on frontend/src/app/mecanico/ajustes/ajustes.page.scss
> +  .ion-text-capitalize{
esto funciona, solo para confirmar?

2024-11-06 23:14 UTC, IgnacioToledoDev commented on frontend/src/app/mecanico/info-car/info-car.page.scss
> +.back-button {
Si este es es el mismo back button que el scannear QR, se deberia omologar en un solo diseño o css, por fa revisar y dejar todos iguales.

Codigo de scannear QR.

 `.back-button {
    position: absolute;
    top: 30px;  // Ajustar la posición
    left: 10px; // Ajustar la posición
    --border-radius: 0px; /* Square corners */
    width: 100%;
    height: 1%;
    --color: #ffffff;
}`

2024-11-06 23:33 UTC, joherrerac commented on frontend/src/app/mecanico/ajustes/ajustes.page.html
> +  <p></p>
Porque a nivel visual se reduce un poco el espacio sobrante en la card en la parte inferior (o por lo menos eso me pude dar cuenta yo).

2024-11-06 23:33 UTC, joherrerac commented on frontend/src/app/mecanico/ajustes/ajustes.page.scss
> +  .ion-text-capitalize{
Si y lo probe tanto en front como en back.

2024-11-06 23:57 UTC, joherrerac commented on frontend/src/app/mecanico/info-car/info-car.page.scss
> +.back-button {
Acabo de probar el codigo que me mandaste y al revisarlo la flecha ya no aparecia visualmente como lo tenia yo antes (mismo problema que tenia el Isaac ayer), por lo que considerando el poco tiempo que nos queda, recomendaria dejarlo como lo tenia previamente.

2024-11-07 00:02 UTC, IgnacioToledoDev commented on frontend/src/app/mecanico/info-car/info-car.page.scss
> +.back-button {
La verdad es que si, pero nos pueden wear si tenemos el componente de diferentes formas prefiero homologarlo para evitar cual problema a futuro y lamentablemente hay que hacerlo. Lo dejare pasar pero te va a quedar como mision

1. Revisar este button en todas las vistas para ver si estan iguales en **size** especialmente

2024-11-07 00:03 UTC, IgnacioToledoDev commented on frontend/src/app/mecanico/ajustes/ajustes.page.html
> +  <p></p>
y haciendo un padding? no se pudo? Por esta vez lo dejare pasar pero porfa mas empeño con el css y html, aunque yo se no es tu fuerte esto es un trabajo que define tu titulo! y se necesita seriedad

2024-11-07 00:04 UTC, merged